language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-22.0.1
    - android-23
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

script: ./gradlew check

cache:
  directories:
    - $HOME/.m2
